version: '2.1'

services:
  web:

    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: mix phoenix.server
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:9.6.1
    volumes:
      - /var/lib/postgresql/data
